export const ACCESS_TOKEN_KEY = 'access_token';

export const MODAL_BODY_TYPES = {
  CONFIRMATION: 'CONFIRMATION',
  VIEW_USER: 'VIEW_USER',
  ADD_NEW_MEMBER: 'ADD_NEW_MEMBER',
  UPDATE_MEMBER: 'UPDATE_MEMBER',
  VIEW_MEMBER: 'VIEW_MEMBER',
  CREATE_SCHEDULE: 'CREATE_SCHEDULE',
  UPDATE_SCHEDULE: 'UPDATE_SCHEDULE',
  UPDATE_CHECKIN: 'UPDATE_CHECKIN',
  CREATE_SCHEDULE_CHECKIN: 'CREATE_SCHEDULE_CHECKIN',
  BROWSE_FILE_MEMBER: 'BROWSE_FILE_MEMBER',
  SHOW_CONFIRM_CHECKIN_MEMBER: 'SHOW_CONFIRM_CHECKIN_MEMBER',
  SHOW_QRCODE: 'SHOW_QRCODE',
  SHOW_CHECKIN_MEMBER: 'SHOW_CHECKIN_MEMBER',
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  SHOW_CHECKIN_MEMBER_FAILED: 'SHOW_CHECKIN_MEMBER_FAILED',
  SHOW_MEMBER_DUPLICATE: 'SHOW_MEMBER_DUPLICATE',
  CONFIRM_DELETE_MEMBER: 'CONFIRM_DELETE_MEMBER',
  RESEND_EMAIL: 'RESEND_EMAIL',
  REMARK_CHECKIN: 'REMARK_CHECKIN',
  SHOW_REMARK: 'SHOW_REMARK',
};
export const CONFIRMATION_MODAL_CLOSE_TYPES = {
  DELETE_USER: 'DELETE_USER',
  DELETE_MEMBER: 'DELETE_MEMBER',
  DELETE_SCHEDULE: 'DELETE_SCHEDULE',
  DELETE_MEMBER_MULTIPLE: 'DELETE_MEMBER_MULTIPLE',
  DELETE_CHECKIN: 'DELETE_CHECKIN',
  SENDMAIL_TO_MEMBER: 'SENDMAIL_TO_MEMBER',
};
